name: AccuKnox DAST Scan Workflow

on:
  push:
    branches:
      - dast

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Accuknox DAST
        uses: accuknox/dast-scan-action@v1.0.0
        with:
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: "cspm.demo.accuknox.com"
          tenant_id: 3730
          label: "SPOC"
          target_url: "http://testphp.vulnweb.com/"
          scan_type: "baseline"          