name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - iac

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Accuknox IaC
        uses: ./action.yaml
        with:
          directory: ./
          output_file_path: ./results
          token: ${{ secrets.ACCUKNOX_TOKEN }}
          endpoint: "cspm.demo.accuknox.com"
          tenant_id: 3730
          quiet: "true"
          label: "tests"
          soft_fail: true

      - name: Upload IaC Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: accuknox-iac-scan-results
          path: ./results
