name: AccuKnox SAST Scan Workflow

on:
  push:
    branches:
      - sast

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Accuknox SAST
        uses: accuknox/sast-scan-opengrep-action@1.0.0
        with:
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: "cspm.demo.accuknox.com"
          accuknox_tenant: 3730
          accuknox_label: "SPOC"
          input_soft_fail: false